import FileInputReadExcel from "@/components/FileInputReadExcel";
import FileInputXLSX from "@/components/FileInputXLSX";
import Head from "next/head";
import "normalize.css/normalize.css";

export default function Home() {
  const handleExcelDataChange = (data: any[][]) => {
    const headers = data[0]; // 첫번째 행을 헤더로 사용
    const rows = data.slice(1); // 첫번째 행을 제외한 나머지 행을 데이터로 사용

    const formattedData = rows.map((row) =>
      headers.reduce((acc, header, index) => {
        acc[header] = row[index];
        return acc;
      }, {})
    );
    console.log(formattedData);
  };

  return (
    <>
      <Head>
        <title>동네문자</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <FileInputXLSX /> */}
      <FileInputReadExcel onChange={handleExcelDataChange} />
    </>
  );
}
